skip_branch_with_pr: false

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests from different categories as separate jobs in parallel
#test:
#  categories:
#    - A            # A category common for all jobs
#    - [UI]         # 1st job
#    - [DAL, BL]    # 2nd job

